
-- Products

CREATE VIEW Products AS
SELECT P.PRODUCT_NAME, P.DESCRIPTION, W.WAREHOUSE_NAME
FROM Project.PRODUCTS P
LEFT JOIN Project.PRODUCTS_IN_WAREHOUSES PW ON P.PRODUCT_ID = PW.PRODUCT_ID
LEFT JOIN Project.WAREHOUSES W ON W.WAREHOUSE_ID = PW.WAREHOUSE_ID
ORDER BY WAREHOUSE_NAME;



-- Employees
CREATE VIEW Employees AS
SELECT E.FIRST_NAME, E.LAST_NAME, W.WAREHOUSE_NAME
FROM Project.EMPLOYEES E 
LEFT JOIN Project.EMPLOYEES_IN_WAREHOUSES EW ON e.EMPLOYEE_ID = ew.EMPLOYEE_ID
LEFT JOIN Project.WAREHOUSES W ON W.WAREHOUSE_ID = ew.WAREHOUSE_ID;


-- Clients with contacts
CREATE VIEW Clients AS
SELECT CON.*, C.CREDIT
FROM Project.CUSTOMERS C 
LEFT JOIN Project.CONTACTS CON ON C.CUSTOMER_ID = CON.CUSTOMER_ID;


-- Categories
CREATE VIEW Product_categories AS
SELECT * FROM Project.PRODUCT_CATEGORIES;

--  Warehouses
CREATE VIEW WAREHOUSES_WITH_LOCATIONS AS
SELECT W.Warehouse_ID, W.WAREHOUSE_NAME, L.*
FROM Project.WAREHOUSES W
LEFT JOIN Project.LOCATIONS L ON W.LOCATION_ID = L.LOCATION_ID
ORDER BY W.WAREHOUSE_ID;

-- Orders
CREATE VIEW Orders AS
SELECT O.*
FROM Project.ORDERS O
